version: "2"
services:

  mysql:
    image: 'mysql:5.6.35'
    ports:
     - "9306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "vmsn2004"
      MYSQL_DATABASE: regalonatural
    volumes:
        - /home/webs/gestion-natural/DB-Gestion-Ralucart:/var/lib/mysql
  php: 
      build: ./docker-php/
      links: 
        - mysql:mysqldb
      volumes: 
        - /home/webs/gestion-natural/Gestion-Ralucart:/var/www/html
  apache: 
    build: ./docker-apache/ 
    links: 
      - php:phpfpm 
    volumes: 
      - /home/webs/gestion-natural/Gestion-Ralucart:/var/www/html
    ports:
      - "8083:80"

